# Generated by Django 3.0.3 on 2020-02-19 14:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UAN', 'Ukrainian hryvnia'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian ruble')], default='USD', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('purchase', models.FloatField()),
                ('selling', models.FloatField()),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
                'get_latest_by': 'start_date',
            },
        ),
    ]
